	    _layouts/.page.html.swp
	    _site/_site/CNAME
	    _site/_site/build.sh
	    _site/_site/clientAPI/api.js
	    _site/_site/clientAPI/assets/css/external-small.png
	    _site/_site/clientAPI/assets/css/logo.png
	    _site/_site/clientAPI/assets/css/main.css
	    _site/_site/clientAPI/assets/favicon.png
	    _site/_site/clientAPI/assets/img/spinner.gif
	    _site/_site/clientAPI/assets/index.html
	    _site/_site/clientAPI/assets/js/api-filter.js
	    _site/_site/clientAPI/assets/js/api-list.js
	    _site/_site/clientAPI/assets/js/api-search.js
	    _site/_site/clientAPI/assets/js/apidocs.js
	    _site/_site/clientAPI/assets/js/yui-prettify.js
	    _site/_site/clientAPI/assets/vendor/prettify/CHANGES.html
	    _site/_site/clientAPI/assets/vendor/prettify/COPYING
	    _site/_site/clientAPI/assets/vendor/prettify/README.html
	    _site/_site/clientAPI/assets/vendor/prettify/prettify-min.css
	    _site/_site/clientAPI/assets/vendor/prettify/prettify-min.js
	    _site/_site/clientAPI/data.json
	    _site/_site/clientAPI/files/hotplate_node_modules_hotDojoDgridWidgets_client_xstyle_load-css.js.html
	    _site/_site/clientAPI/files/hotplate_node_modules_hotDojoDgridWidgets_client_xstyle_load-imports.js.html
	    _site/_site/clientAPI/index.html
	    _site/_site/guide.html
	    _site/_site/guide.md
	    _site/_site/hotplate/GUIDE.md
	    _site/_site/hotplate/LICENSE.txt
	    _site/_site/hotplate/README.md
	    _site/_site/hotplate/TODO.txt
	    _site/_site/hotplate/counter.sh
	    _site/_site/hotplate/hotplate.js
	    _site/_site/hotplate/node_modules/hotCoreAuth/enabled
	    _site/_site/hotplate/node_modules/hotCoreAuth/lib/auth/facebook.js
	    _site/_site/hotplate/node_modules/hotCoreAuth/lib/auth/local.js
	    _site/_site/hotplate/node_modules/hotCoreAuth/lib/hotCoreAuth.js
	    _site/_site/hotplate/node_modules/hotCoreAuth/package.json
	    _site/_site/hotplate/node_modules/hotCoreClientFiles/client/one.css
	    _site/_site/hotplate/node_modules/hotCoreClientFiles/enabled
	    _site/_site/hotplate/node_modules/hotCoreClientFiles/lib/hotCoreClientFiles.js
	    _site/_site/hotplate/node_modules/hotCoreClientFiles/package.json
	    _site/_site/hotplate/node_modules/hotCoreCometMessages/TODO.txt
	    _site/_site/hotplate/node_modules/hotCoreCometMessages/enabled
	    _site/_site/hotplate/node_modules/hotCoreCometMessages/lib/hotCoreCometMessages-ORIG.js
	    _site/_site/hotplate/node_modules/hotCoreCometMessages/lib/hotCoreCometMessages.js
	    _site/_site/hotplate/node_modules/hotCoreCometMessages/package.json
	    _site/_site/hotplate/node_modules/hotCoreCommonValidators/enabled
	    _site/_site/hotplate/node_modules/hotCoreCommonValidators/lib/hotCoreCommonValidators.js
	    _site/_site/hotplate/node_modules/hotCoreCommonValidators/package.json
	    _site/_site/hotplate/node_modules/hotCoreError/enabled
	    _site/_site/hotplate/node_modules/hotCoreError/lib/hotCoreError.js
	    _site/_site/hotplate/node_modules/hotCoreError/package.json
	    _site/_site/hotplate/node_modules/hotCoreHandyCss/client/handyCss.css
	    _site/_site/hotplate/node_modules/hotCoreHandyCss/enabled
	    _site/_site/hotplate/node_modules/hotCoreHandyCss/lib/hotCoreHandyCss.js
	    _site/_site/hotplate/node_modules/hotCoreHandyCss/package.json
	    _site/_site/hotplate/node_modules/hotCoreJsonRestStores/enabled
	    _site/_site/hotplate/node_modules/hotCoreJsonRestStores/lib/hotCoreJsonRestStores.js
	    _site/_site/hotplate/node_modules/hotCoreJsonRestStores/package.json
	    _site/_site/hotplate/node_modules/hotCoreMultiHome/enabled
	    _site/_site/hotplate/node_modules/hotCoreMultiHome/lib/hotCoreMultiHome.js
	    _site/_site/hotplate/node_modules/hotCoreMultiHome/package.json
	    _site/_site/hotplate/node_modules/hotCorePage/client/one.css
	    _site/_site/hotplate/node_modules/hotCorePage/enabled
	    _site/_site/hotplate/node_modules/hotCorePage/lib/Csses.js
	    _site/_site/hotplate/node_modules/hotCorePage/lib/HeadLines.js
	    _site/_site/hotplate/node_modules/hotCorePage/lib/Jses.js
	    _site/_site/hotplate/node_modules/hotCorePage/lib/Vars.js
	    _site/_site/hotplate/node_modules/hotCorePage/lib/hotCorePage.js
	    _site/_site/hotplate/node_modules/hotCorePage/package.json
	    _site/_site/hotplate/node_modules/hotCoreProtocol/client/hotFixErrorResponse.js
	    _site/_site/hotplate/node_modules/hotCoreProtocol/enabled
	    _site/_site/hotplate/node_modules/hotCoreProtocol/lib/hotCoreProtocol.js
	    _site/_site/hotplate/node_modules/hotCoreProtocol/package.json
	    _site/_site/hotplate/node_modules/hotCoreServerLogger/enabled
	    _site/_site/hotplate/node_modules/hotCoreServerLogger/lib/hotCoreServerLogger.js
	    _site/_site/hotplate/node_modules/hotCoreServerLogger/package.json
	    _site/_site/hotplate/node_modules/hotCoreSharedCode/enabled
	    _site/_site/hotplate/node_modules/hotCoreSharedCode/lib/hotCoreSharedCode.js
	    _site/_site/hotplate/node_modules/hotCoreSharedCode/package.json
	    _site/_site/hotplate/node_modules/hotCoreStoreConfig/enabled
	    _site/_site/hotplate/node_modules/hotCoreStoreConfig/lib/hotCoreStoreConfig.js
	    _site/_site/hotplate/node_modules/hotCoreStoreConfig/package.json
	    _site/_site/hotplate/node_modules/hotCoreStoreExposer/enabled
	    _site/_site/hotplate/node_modules/hotCoreStoreExposer/lib/hotCoreStoreExposer.js
	    _site/_site/hotplate/node_modules/hotCoreStoreExposer/package.json
	    _site/_site/hotplate/node_modules/hotCoreStoreLogger/enabled
	    _site/_site/hotplate/node_modules/hotCoreStoreLogger/lib/hotCoreStoreLogger.js
	    _site/_site/hotplate/node_modules/hotCoreStoreLogger/package.json
	    _site/_site/hotplate/node_modules/hotCoreStoreRegistry/enabled
	    _site/_site/hotplate/node_modules/hotCoreStoreRegistry/lib/hotCoreStoreRegistry.js
	    _site/_site/hotplate/node_modules/hotCoreStoreRegistry/package.json
	    _site/_site/hotplate/node_modules/hotCoreStoreVars/enabled
	    _site/_site/hotplate/node_modules/hotCoreStoreVars/lib/hotCoreStoreVars.js
	    _site/_site/hotplate/node_modules/hotCoreStoreVars/package.json
	    _site/_site/hotplate/node_modules/hotDojo/client/blank.html
	    _site/_site/hotplate/node_modules/hotDojo/enabled
	    _site/_site/hotplate/node_modules/hotDojo/lib/hotDojo.js
	    _site/_site/hotplate/node_modules/hotDojo/package.json
	    _site/_site/hotplate/node_modules/hotDojoAppContainer/client/AppContainer.js
	    _site/_site/hotplate/node_modules/hotDojoAppContainer/client/mainContainer.css
	    _site/_site/hotplate/node_modules/hotDojoAppContainer/client/mainContainer.js
	    _site/_site/hotplate/node_modules/hotDojoAppContainer/enabled
	    _site/_site/hotplate/node_modules/hotDojoAppContainer/lib/hotDojoAppContainer.js
	    _site/_site/hotplate/node_modules/hotDojoAppContainer/package.json
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/NewWorkspace.js
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/Pick.js
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/ValidationUsername.js
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/ValidationWorkspace.js
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/Welcome.js
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/auth.css
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/auth/facebook.js
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/auth/facebook.png
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/auth/img/noaccess.png
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/auth/img/tick.png
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/auth/local.js
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/auth/local.png
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/mainPick.js
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/mainWelcome.js
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/panels/Manager.js
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/panels/Resume.js
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/panels/SignInRecoverRegister.js
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/pick.css
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/templates/NewWorkspace.html
	    _site/_site/hotplate/node_modules/hotDojoAuth/client/welcome.css
	    _site/_site/hotplate/node_modules/hotDojoAuth/enabled
	    _site/_site/hotplate/node_modules/hotDojoAuth/lib/hotDojoAuth.js
	    _site/_site/hotplate/node_modules/hotDojoAuth/package.json
	    _site/_site/hotplate/node_modules/hotDojoCometMessages/client/messages-OLD.js
	    _site/_site/hotplate/node_modules/hotDojoCometMessages/client/messages.js
	    _site/_site/hotplate/node_modules/hotDojoCometMessages/enabled
	    _site/_site/hotplate/node_modules/hotDojoCometMessages/lib/hotDojoCometMessages.js
	    _site/_site/hotplate/node_modules/hotDojoCometMessages/package.json
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/EditableList.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/EditableList.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/StoreSelect.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/StoreSelect.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/CHANGES.md
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/CellSelection.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/ColumnSet.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/Grid.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/GridFromHtml.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/GridWithColumnSetsFromHtml.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/Keyboard.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/LICENSE
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/List.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/OnDemandGrid.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/OnDemandList.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/README.md
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/Selection.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/TouchScroll.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/TouchScroll.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/columnset.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/dgrid.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/dgrid_rtl.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/extensions/ColumnHider.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/extensions/ColumnReorder.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/extensions/ColumnResizer.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/extensions/CompoundColumns.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/extensions/Pagination.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/has-transforms3d.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/images/ui-icons_222222_256x240.png
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/images/ui-icons_222222_256x240_white.png
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/skins/README.md
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/skins/cactus.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/skins/claro.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/skins/images/row_back.png
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/skins/nihilo.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/skins/sage.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/skins/slate.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/skins/soria.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/skins/squid.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/css/skins/tundra.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/demos/dTuned/data.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/demos/dTuned/index.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/demos/dTuned/resources/dTuned.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/demos/dTuned/resources/images/grid-header-bg.png
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/demos/dTuned/resources/images/grid-header-separator.png
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/demos/dTuned/resources/images/grid-header-sorted-separator.png
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/demos/dTuned/resources/images/grid-header-sorted.png
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/demos/dTuned/resources/images/header-background.png
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/demos/dTuned/resources/images/header.png
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/demos/multiview/index.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/demos/multiview/resources/df-128.png
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/demos/multiview/resources/df-32.png
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/demos/multiview/resources/df-64.png
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/demos/multiview/resources/dojo-128.png
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/demos/multiview/resources/dojo-32.png
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/demos/multiview/resources/dojo-64.png
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/demos/todo/index.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/editor.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/extensions/ColumnHider.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/extensions/ColumnReorder.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/extensions/ColumnResizer.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/extensions/CompoundColumns.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/extensions/DijitRegistry.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/extensions/DnD.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/extensions/Pagination.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/extensions/nls/es/pagination.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/extensions/nls/fr/pagination.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/extensions/nls/ja/pagination.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/extensions/nls/pagination.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/extensions/nls/pt/pagination.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/extensions/nls/sk/pagination.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/package.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/package.json
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/selector.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/GridFromHtml.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/GridFromHtml_Editors.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/Grid_headerless.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/Grid_mouseevents.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/Grid_rendering.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/JsonRest.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/JsonRest_duplicates.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/Keyboard.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/OnDemand.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/OnDemand_promises.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/OnDemand_tile.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/Selection.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/autoheight.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/common_cases.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/complex_column.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/data/DeferredWrapper.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/data/base.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/data/createIndex.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/data/errorStores.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/data/index.json
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/data/perf.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/data/rest.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/data/rest.php
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/dijit_layout.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/dijit_layout_mixed.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/dijit_layout_programmatic.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/doh/addCssRule.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/doh/create-destroy.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/doh/module.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/doh/runTests.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/doh/stores.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/editor.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/editor_more_widgets.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/editor_no_store.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/editor_widgets.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/extensions/ColumnHider.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/extensions/ColumnHider_MenuHeight.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/extensions/ColumnReorder.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/extensions/ColumnReorder_complex.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/extensions/ColumnResizer.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/extensions/ColumnResizer_complex.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/extensions/CompoundColumns.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/extensions/DnD.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/extensions/DnD_touch.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/extensions/DnD_tree.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/extensions/Pagination.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/extensions/Pagination_i18n.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/extensions/Pagination_tree.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/has-css3.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/index.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/mobile_grid.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/performance.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/performance_dojox_datagrid.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/performance_slow_network.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/performance_widgets.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/rtl.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/selector.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/set_class.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/simple_grid.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/skin.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/sparse_sort.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/tree.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/tree_editor.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/tree_expand.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/tree_expand_hidden.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/tundra_custom.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/test/widths.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/tree.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/util/has-css3.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/util/misc.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/util/mouse.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/dgrid/util/touch.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/put-selector/LICENSE
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/put-selector/README.md
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/put-selector/node-html.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/put-selector/package.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/put-selector/package.json
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/put-selector/put.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/put-selector/test/example-server.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/put-selector/test/node-put.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/put-selector/test/put.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/put-selector/test/testPut.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/LICENSE
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/README.md
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/build.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/build/amd-css.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/build/sample-dojo-profile.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/css.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/ext.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/ext/bind.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/ext/event-delegate.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/ext/event.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/ext/scrollbar.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/ext/supported.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/ext/widget.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/has-class.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/index.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/load-css.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/load-imports.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/package.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/package.json
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/shim/boxOffsets.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/shim/gradient.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/shim/ie-filter.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/shim/inlineBlock.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/shim/pseudo.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/shim/transition.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/shim/var.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/shims.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/test/converter.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/test/gh-index.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/test/gh-ui.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/test/html5elements.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/test/put.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/test/shims.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/test/standalone.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/test/test-data.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/test/testDijit.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/test/testDijit.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/test/testHtml5Elements.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/test/testPut.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/test/testShims.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/test/try-it.html
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/util/createStyleSheet.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/x.css
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/client/xstyle/xstyle.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/enabled
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/lib/hotDojoDgridWidgets.js
	    _site/_site/hotplate/node_modules/hotDojoDgridWidgets/package.json
	    _site/_site/hotplate/node_modules/hotDojoGlobalAlertBar/client/mainAlertBar.js
	    _site/_site/hotplate/node_modules/hotDojoGlobalAlertBar/enabled
	    _site/_site/hotplate/node_modules/hotDojoGlobalAlertBar/lib/hotDojoGlobalAlertBar.js
	    _site/_site/hotplate/node_modules/hotDojoGlobalAlertBar/package.json
	    _site/_site/hotplate/node_modules/hotDojoGlobals/client/globals.js
	    _site/_site/hotplate/node_modules/hotDojoGlobals/enabled
	    _site/_site/hotplate/node_modules/hotDojoGlobals/lib/hotDojoGlobals.js
	    _site/_site/hotplate/node_modules/hotDojoGlobals/package.json
	    _site/_site/hotplate/node_modules/hotDojoLogger/client/logger.js
	    _site/_site/hotplate/node_modules/hotDojoLogger/enabled
	    _site/_site/hotplate/node_modules/hotDojoLogger/lib/hotDojoLogger.js
	    _site/_site/hotplate/node_modules/hotDojoLogger/package.json
	    _site/_site/hotplate/node_modules/hotDojoStoreConfig/client/ConfigVars.js
	    _site/_site/hotplate/node_modules/hotDojoStoreConfig/enabled
	    _site/_site/hotplate/node_modules/hotDojoStoreConfig/lib/hotDojoStoreConfig.js
	    _site/_site/hotplate/node_modules/hotDojoStoreConfig/package.json
	    _site/_site/hotplate/node_modules/hotDojoStores/client/AppStoreNotify.js
	    _site/_site/hotplate/node_modules/hotDojoStores/client/Cache.js
	    _site/_site/hotplate/node_modules/hotDojoStores/client/JsonObservable.js
	    _site/_site/hotplate/node_modules/hotDojoStores/client/JsonRest.js
	    _site/_site/hotplate/node_modules/hotDojoStores/client/stores.js
	    _site/_site/hotplate/node_modules/hotDojoStores/enabled
	    _site/_site/hotplate/node_modules/hotDojoStores/lib/hotDojoStores.js
	    _site/_site/hotplate/node_modules/hotDojoStores/package.json
	    _site/_site/hotplate/node_modules/hotDojoSubmit/client/defaultSubmit.js
	    _site/_site/hotplate/node_modules/hotDojoSubmit/enabled
	    _site/_site/hotplate/node_modules/hotDojoSubmit/lib/hotDojoSubmit.js
	    _site/_site/hotplate/node_modules/hotDojoSubmit/package.json
	    _site/_site/hotplate/node_modules/hotDojoWidgetHooks/client/SyncSubscriber.js
	    _site/_site/hotplate/node_modules/hotDojoWidgetHooks/client/SyncTopic.js
	    _site/_site/hotplate/node_modules/hotDojoWidgetHooks/enabled
	    _site/_site/hotplate/node_modules/hotDojoWidgetHooks/lib/hotDojoWidgetHooks.js
	    _site/_site/hotplate/node_modules/hotDojoWidgetHooks/package.json
	    _site/_site/hotplate/node_modules/hotDojoWidgets/client/AlertBar.css
	    _site/_site/hotplate/node_modules/hotDojoWidgets/client/AlertBar.js
	    _site/_site/hotplate/node_modules/hotDojoWidgets/client/BusyButton.js
	    _site/_site/hotplate/node_modules/hotDojoWidgets/client/ConfirmDialog.js
	    _site/_site/hotplate/node_modules/hotDojoWidgets/client/EditingWidget.css
	    _site/_site/hotplate/node_modules/hotDojoWidgets/client/EditingWidget.js
	    _site/_site/hotplate/node_modules/hotDojoWidgets/client/StackFading.js
	    _site/_site/hotplate/node_modules/hotDojoWidgets/client/TabFading.js
	    _site/_site/hotplate/node_modules/hotDojoWidgets/client/TempDialog.js
	    _site/_site/hotplate/node_modules/hotDojoWidgets/enabled
	    _site/_site/hotplate/node_modules/hotDojoWidgets/lib/hotDojoWidgets.js
	    _site/_site/hotplate/node_modules/hotDojoWidgets/package.json
	    _site/_site/hotplate/package.json
	    _site/_site/images/bg_hr.png
	    _site/_site/images/blacktocat.png
	    _site/_site/images/checker.png
	    _site/_site/images/icon_download.png
	    _site/_site/images/sprite_download.png
	    _site/_site/index.html
	    _site/_site/index.md
	    _site/_site/javascripts/main.js
	    _site/_site/javascripts/scale.fix.js
	    _site/_site/params.json
	    _site/_site/serverAPI/api.js
	    _site/_site/serverAPI/assets/css/external-small.png
	    _site/_site/serverAPI/assets/css/logo.png
	    _site/_site/serverAPI/assets/css/main.css
	    _site/_site/serverAPI/assets/favicon.png
	    _site/_site/serverAPI/assets/img/spinner.gif
	    _site/_site/serverAPI/assets/index.html
	    _site/_site/serverAPI/assets/js/api-filter.js
	    _site/_site/serverAPI/assets/js/api-list.js
	    _site/_site/serverAPI/assets/js/api-search.js
	    _site/_site/serverAPI/assets/js/apidocs.js
	    _site/_site/serverAPI/assets/js/yui-prettify.js
	    _site/_site/serverAPI/assets/vendor/prettify/CHANGES.html
	    _site/_site/serverAPI/assets/vendor/prettify/COPYING
	    _site/_site/serverAPI/assets/vendor/prettify/README.html
	    _site/_site/serverAPI/assets/vendor/prettify/prettify-min.css
	    _site/_site/serverAPI/assets/vendor/prettify/prettify-min.js
	    _site/_site/serverAPI/classes/hotCoreAuth.facebook.html
	    _site/_site/serverAPI/classes/hotCoreAuth.html
	    _site/_site/serverAPI/classes/hotCoreClientFiles.html
	    _site/_site/serverAPI/data.json
	    _site/_site/serverAPI/files/hotplate_node_modules_hotCoreAuth_lib_auth_facebook.js.html
	    _site/_site/serverAPI/files/hotplate_node_modules_hotCoreAuth_lib_hotCoreAuth.js.html
	    _site/_site/serverAPI/files/hotplate_node_modules_hotCoreClientFiles_lib_hotCoreClientFiles.js.html
	    _site/_site/serverAPI/files/hotplate_node_modules_hotCorePage_lib_Csses.js.html
	    _site/_site/serverAPI/files/hotplate_node_modules_hotCorePage_lib_HeadLines.js.html
	    _site/_site/serverAPI/files/hotplate_node_modules_hotCorePage_lib_Jses.js.html
	    _site/_site/serverAPI/files/hotplate_node_modules_hotCorePage_lib_Vars.js.html
	    _site/_site/serverAPI/index.html
	    _site/_site/serverAPI/modules/hotCoreAuth.html
	    _site/_site/serverAPI/modules/hotCoreClientFiles.html
	    _site/_site/stylesheets/pygment_trac.css
	    _site/_site/stylesheets/styles.css
	    _site/_site/stylesheets/stylesheet.css
	    _site/guide.md
	    _site/index.md
	    _site/serverAPI/files/hotplate_node_modules_hotDojoDgridWidgets_client_xstyle_load-css.js.html
	    _site/serverAPI/files/hotplate_node_modules_hotDojoDgridWidgets_client_xstyle_load-imports.js.html
	    _yuidocThemes/client/layouts/.main.handlebars.swp
	    _yuidocThemes/server/assets/css/.weblookalike.css.swp
	    _yuidocThemes/server/layouts/.main.handlebars.swp
	    serverAPI/assets/css/.weblookalike.css.swp
	    serverAPI/files/.._hotplate_node_modules_hotCoreAuth_lib_auth_facebook.js.html
	    serverAPI/files/.._hotplate_node_modules_hotCoreAuth_lib_hotCoreAuth.js.html
	    serverAPI/files/.._hotplate_node_modules_hotCoreClientFiles_lib_hotCoreClientFiles.js.html
	    serverAPI/files/.._hotplate_node_modules_hotCorePage_lib_Csses.js.html
	    serverAPI/files/.._hotplate_node_modules_hotCorePage_lib_HeadLines.js.html
	    serverAPI/files/.._hotplate_node_modules_hotCorePage_lib_Jses.js.html
	    serverAPI/files/.._hotplate_node_modules_hotCorePage_lib_Vars.js.html
	    serverAPI/files/hotplate_node_modules_hotDojoDgridWidgets_client_xstyle_load-css.js.html
	    serverAPI/files/hotplate_node_modules_hotDojoDgridWidgets_client_xstyle_load-imports.js.html
